const cities = [
  "New York City, NY", "Los Angeles, CA", "Chicago, IL", "Houston, TX", "Phoenix, AZ",
  "Philadelphia, PA", "San Antonio, TX", "San Diego, CA", "Dallas, TX", "Austin, TX",
  "Jacksonville, FL", "Fort Worth, TX", "San Jose, CA", "Columbus, OH", "Charlotte, NC",
  "Indianapolis, IN", "Seattle, WA", "San Francisco, CA", "Denver, CO", "Oklahoma City, OK",
  "El Paso, TX", "Nashville, TN", "Las Vegas, NV", "Washington, DC", "Memphis, TN",
  "Louisville, KY", "Detroit, MI", "Portland, OR", "Boston, MA", "Baltimore, MD",
  "Albuquerque, NM", "Milwaukee, WI", "Fresno, CA", "Tucson, AZ", "Sacramento, CA",
  "Mesa, AZ", "Kansas City, MO", "Colorado Springs, CO", "Atlanta, GA", "Omaha, NE",
  "Raleigh, NC", "Virginia Beach, VA", "Long Beach, CA", "Miami, FL", "Oakland, CA",
  "Minneapolis, MN", "Bakersfield, CA", "Tulsa, OK", "Aurora, CO", "Tampa, FL",
  "Wichita, KS", "Arlington, TX", "New Orleans, LA", "Cleveland, OH", "Anaheim, CA",
  "Honolulu, HI", "Henderson, NV", "Stockton, CA", "Riverside, CA", "Lexington, KY",
  "Corpus Christi, TX", "Irvine, CA", "Orlando, FL", "Santa Ana, CA", "Cincinnati, OH",
  "Newark, NJ", "St. Paul, MN", "Greensboro, NC", "Pittsburgh, PA", "Lincoln, NE",
  "North Las Vegas, NV", "Plano, TX", "Durham, NC", "Chandler, AZ", "Anchorage, AK",
  "Gilbert, AZ", "St. Louis, MO", "Chula Vista, CA", "Reno, NV", "Buffalo, NY",
  "Madison, WI", "Fort Wayne, IN", "Jersey City, NJ", "Lubbock, TX", "Toledo, OH",
  "Laredo, TX", "St. Petersburg, FL", "Chesapeake, VA", "Winston-Salem, NC", "Glendale, AZ",
  "Irving, TX", "Scottsdale, AZ", "Port St. Lucie, FL", "Norfolk, VA", "Chattanooga, TN",
  "Providence, RI", "Salt Lake City, UT", "Huntsville, AL", "Tempe, AZ", "Worcester, MA",
  "Fayetteville, NC", "Cape Coral, FL", "Brownsville, TX", "McKinney, TX", "Sioux Falls, SD",
  "Frisco, TX", "Boise, ID", "Knoxville, TN", "Grand Rapids, MI", "Newport News, VA",
  "Little Rock, AR", "Moreno Valley, CA", "Oxnard, CA", "Des Moines, IA", "Jackson, MS",
  "Amarillo, TX", "Fontana, CA", "Rochester, NY", "Huntington Beach, CA", "Salt Lake City, UT",
  "Grand Prairie, TX", "Columbus, GA", "Yonkers, NY", "Montgomery, AL", "Augusta, GA",
  "Aurora, IL", "Akron, OH", "Little Rock, AR", "Shreveport, LA", "Mobile, AL",
  "Columbus, GA", "Glendale, CA", "Tacoma, WA", "Amarillo, TX", "Huntington Beach, CA",
  "Fontana, CA", "Oxnard, CA", "Aurora, IL", "Moreno Valley, CA", "Fayetteville, NC",
  "Rochester, NY", "Modesto, CA", "Akron, OH", "San Bernardino, CA", "Spokane, WA",
  "Birmingham, AL", "Richmond, VA", "Boise, ID", "Baton Rouge, LA", "Des Moines, IA",
  "Spokane, WA", "Glendale, CA", "Tacoma, WA", "San Bernardino, CA", "Modesto, CA",
  "Fontana, CA", "Des Moines, IA", "Moreno Valley, CA", "Santa Clarita, CA", "Fayetteville, NC",
  "Birmingham, AL", "Oceanside, CA", "Rochester, NY", "Port St. Lucie, FL", "Grand Rapids, MI",
  "Huntington Beach, CA", "Newport News, VA", "Chattanooga, TN", "Fort Lauderdale, FL", "Rancho Cucamonga, CA",
  "Santa Rosa, CA", "Peoria, AZ", "Oceanside, CA", "Elk Grove, CA", "Salem, OR",
  "Pembroke Pines, FL", "Eugene, OR", "Ontario, CA", "Garden Grove, CA", "Corona, CA",
  "Cary, NC", "Springfield, MO", "Fort Collins, CO", "Jackson, MS", "Alexandria, VA",
  "Hayward, CA", "Lancaster, CA", "Lakewood, CO", "Clarksville, TN", "Palmdale, CA",
  "Salinas, CA", "Springfield, MA", "Hollywood, FL", "Pasadena, TX", "Sunnyvale, CA",
  "Macon, GA", "Kansas City, KS", "Pomona, CA", "Escondido, CA", "Killeen, TX",
  "Naperville, IL", "Joliet, IL", "Bellevue, WA", "Rockford, IL", "Savannah, GA",
  "Paterson, NJ", "Torrance, CA", "Bridgeport, CT", "McAllen, TX", "Mesquite, TX",
  "Syracuse, NY", "Midland, TX", "Pasadena, CA", "Murfreesboro, TN", "Miramar, FL",
  "Dayton, OH", "Fullerton, CA", "Olathe, KS", "Orange, CA", "Thornton, CO",
  "Roseville, CA", "Denton, TX", "Waco, TX", "Surprise, AZ", "Carrollton, TX",
  "West Valley City, UT", "Charleston, SC", "Warren, MI", "Hampton, VA", "Gainesville, FL",
  "Visalia, CA", "Coral Springs, FL", "Columbia, SC", "Cedar Rapids, IA", "Sterling Heights, MI",
  "New Haven, CT", "Stamford, CT", "Concord, CA", "Kent, WA", "Santa Clara, CA",
  "Elizabeth, NJ", "Round Rock, TX", "Thousand Oaks, CA", "Lafayette, LA", "Athens, GA",
  "Topeka, KS", "Simi Valley, CA", "Fargo, ND", "Norman, OK", "Columbia, MO",
  "Abilene, TX", "Wilmington, NC", "Hartford, CT", "Victorville, CA", "Pearland, TX",
  "Vallejo, CA", "Ann Arbor, MI", "Berkeley, CA", "Allentown, PA", "Richardson, TX",
  "Odessa, TX", "Arvada, CO", "Cambridge, MA", "Sugar Land, TX", "Beaumont, TX",
  "Lansing, MI", "Evansville, IN", "Rochester, MN", "Independence, MO", "Fairfield, CA",
  "Provo, UT", "Clearwater, FL", "College Station, TX", "West Jordan, UT", "Carlsbad, CA",
  "El Monte, CA", "Murrieta, CA", "Temecula, CA", "Springfield, IL", "Palm Bay, FL",
  "Costa Mesa, CA", "Westminster, CO", "North Charleston, SC", "Miami Gardens, FL", "Manchester, NH",
  "High Point, NC", "Downey, CA", "Clovis, CA", "Pompano Beach, FL", "Pueblo, CO",
  "Elgin, IL", "Lowell, MA", "Antioch, CA", "West Palm Beach, FL", "Peoria, IL",
  "Everett, WA", "Wichita Falls, TX", "Green Bay, WI", "Daly City, CA", "Burbank, CA",
  "Richardson, TX", "Palm Coast, FL", "Billings, MT", "Centennial, CO", "Temecula, CA",
  "San Mateo, CA", "Springdale, AR", "Denton, TX", "Erie, PA", "South Bend, IN"
];
const cityOptions = cities.map(city => ({ value: city, label: city }));

export default cityOptions;